### PR TITLE
[UPDATE] enable execution by switching to use myst_nb (OLD TESTING BRANCH)

### PR DESCRIPTION
**Pull request by mmcky**
Switches on `myst_nb` to support execution of code

### CODE REVIEW

**Comment by mmcky** [comment]
This will need https://github.com/mmcky/sphinxcontrib-tomyst/issues/46 to be supported.

**Comment by mmcky** [comment]
Will need to use:

- [ ] myst_nb rather than myst_parser
- [ ] will need to remove `jupyter_` settings from `sphinxcontrib-jupyter` due to name collisions (manually)

**Comment by mmcky** [comment]
Getting some issues:

```bash
▶ make clean && make html
Removing everything under '_build'...
Running Sphinx v3.1.2
making output directory... done
WARNING: unknown config value 'jupyter_allow_html_only' in override, ignoring
myst v0.12.9: MdParserConfig(renderer='sphinx', commonmark_only=False, dmath_enable=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, amsmath_enable=False, deflist_enable=False, update_mathjax=True, admonition_enable=False, figure_enable=False, disable_syntax=[], html_img_enable=False, url_schemes=None, heading_anchors=None)
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 27 source files that are out of date
updating environment: executing outdated notebooks... failed

Extension error:
Handler <function update_execution_cache at 0x7fe945c5daf0> for event 'env-get-outdated' threw an exception
make: *** [html] Error 2
```

and looks like `jupytext` has an issue with converting the `md` files. 

```bash
[jupytext] Reading getting_started.md in format md
Traceback (most recent call last):
  File "/Users/matthewmckay/anaconda3/envs/tomyst/bin/jupytext", line 8, in <module>
    sys.exit(jupytext())
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/jupytext/cli.py", line 402, in jupytext
    exit_code += jupytext_single_file(nb_file, args, log)
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/jupytext/cli.py", line 458, in jupytext_single_file
    notebook = read(nb_file, fmt=fmt)
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/jupytext/jupytext.py", line 399, in read
    return read(stream, as_version=as_version, fmt=fmt, **kwargs)
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/jupytext/jupytext.py", line 408, in read
    return reads(fp.read(), fmt, **kwargs)
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/jupytext/jupytext.py", line 360, in reads
    notebook = reader.reads(text, **kwargs)
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/jupytext/jupytext.py", line 79, in reads
    return myst_to_notebook(s)
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/jupytext/myst.py", line 279, in myst_to_notebook
    tokens = get_parser().parse(text + "\n")
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/markdown_it/main.py", line 229, in parse
    self.core.process(state)
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/markdown_it/parser_core.py", line 33, in process
    rule(state)
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/markdown_it/rules_core/block.py", line 14, in block
    state.md.block.parse(
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/markdown_it/parser_block.py", line 100, in parse
    self.tokenize(state, state.line, state.lineMax)
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/markdown_it/parser_block.py", line 77, in tokenize
    if rule(state, line, endLine, False):
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/markdown_it/rules_block/list.py", line 264, in list_block
    state.md.block.tokenize(state, startLine, endLine)
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/markdown_it/parser_block.py", line 58, in tokenize
    state.line = line = state.skipEmptyLines(line)
  File "/Users/matthewmckay/anaconda3/envs/tomyst/lib/python3.8/site-packages/markdown_it/rules_block/state_block.py", line 134, in skipEmptyLines
    if (self.bMarks[from_pos] + self.tShift[from_pos]) < self.eMarks[from_pos]:
IndexError: list index out of range
```

The files include `code-block` directives at the moment (rather than `code-cell`) but even if `jupytext` doesn't interpret `code-block` I wouldn't expect these to fail.

**Comment by mmcky** [comment]
- [x] Add support for writing `code-cell` directives if targeting `jupytext` compatible document (done in https://github.com/mmcky/sphinxcontrib-tomyst/pull/48)

**Comment by chrisjsewell** [comment]
This is a markdown-it-py bug.
At a guess due to a porting "discrepancy" with the JavaScript code, which returns `undefined` rather than raising an `IndexError` if you try asking for the index of a list with too few entries.
Ideally narrow down the bug to a minimal piece of text, so we can make a test case for it and fix.
(it looks like its during the parsing of a list)

**Comment by mmcky** [comment]
This https://github.com/mmcky/sphinxcontrib-tomyst/pull/48 doesn't fix it either which updates `code-block` to `code-cell`

**Comment by mmcky** [comment]
@chrisjsewell OK I have a minimal example for the `jupytext` issue but not high priority. 

It is a strange bug and has to do with a complex list **and** spacing at the end of the document. If this list (which granted isn't nice input -- was generated by `tomyst` -- but is valid markdown as far as I can tell) is in a file with only one empty newline at the end of the document then it builds fine via `jupytext` -- however `n>1` empty lines at the end of the document causes the error above (IndexError). 

[example.md.zip](https://github.com/QuantEcon/lecture-python-programming.myst/files/5228948/example.md.zip)

**Comment by mmcky** [comment]
Execution is currently failing for:

```bash
WARNING: Execution Failed: /lecture-python-programming.myst/source/rst/pandas.md
WARNING: Execution Failed: /lecture-python-programming.myst/source/rst/python_by_example.md
WARNING: Execution Failed: /lecture-python-programming.myst/source/rst/python_advanced_features.md
WARNING: Execution Failed: /lecture-python-programming.myst/source/rst/debugging.md
WARNING: Execution Failed: /lecture-python-programming.myst/source/rst/need_for_speed.md
WARNING: Execution Failed: /lecture-python-programming.myst/source/rst/oop_intro.md
WARNING: Execution Failed: /lecture-python-programming.myst/source/rst/python_essentials.md
WARNING: Execution Failed: /lecture-python-programming.myst/source/rst/python_oop.md
```

**Comment by mmcky** [comment]
- [ ] reported issue to `jupyter-cache`: https://github.com/executablebooks/jupyter-cache/issues/60

**Comment by mmcky** [comment]
Also -- even with execution failures this project built and deployed -- is that the correct default behaviour?

**Comment by chrisjsewell** [comment]
> Also -- even with execution failures this project built and deployed -- is that the correct default behaviour?

As with every sphinx project (and jupyter-book), you should always run production sphinx-build with the options `-n -W —keep-going`, which is what e.g. RTD uses https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-fail-on-warning

**Comment by mmcky** [comment]
thanks @chrisjsewell -- will enable that on production / publish workloads.

**Comment by mmcky** [comment]
This currently manually renames

- [ ] scipy, pandas, numpy, numba and matplotlib to prepend each lecture name with `lect_`
- [ ] manually updated `conf.py` to enable execution (should add config when using `target_jupytext=True`

only one failing lecture

```
WARNING: Execution Failed: lecture-python-programming.myst/source/rst/python_advanced_features.md
```

**Pull request closed without merging**
