### PR TITLE
ENH: Add GitHub Action based Link checker

### PR DESCRIPTION
**Pull request by mmcky**
This PR enables a link check run for the website based on GitHub Actions workflow

It will also run when a PR is opened.

### CODE REVIEW

**Comment by mmcky** [comment]
@HumphreyYang I am adding a link checker to this repository and will roll it out to the other lecture sites one we fine tune the workflows. There are a couple of `broken` links

```

parallelization.md:345: [broken] https://python-intro.quantecon.org/finite_markov.html#Ergodicity: Anchor 'Ergodicity' not found
about_py.md:477: [broken] https://www.dask.org/: 525 Server Error:  for url: https://www.dask.org/
python_essentials.md:626: [redirected with Found] https://www.python.org/dev/peps/pep-0008/ to https://peps.python.org/pep-0008/
```

would you mind to look at those and fix them on this branch. Then I will reopen this PR and trigger another run of the link checker to see if it fails on `permanent redirects` also.

**Comment by mmcky** [comment]
Thanks @HumphreyYang this looks great. Link Checker is passing now. Thanks.

**Comment by mmcky** [comment]
Looking at the diff did you update the redirects as well?

**Comment by HumphreyYang** [comment]
> @HumphreyYang I am adding a link checker to this repository and will roll it out to the other lecture sites one we fine tune the workflows. There are a couple of `broken` links
> 
> ```
> 
> parallelization.md:345: [broken] https://python-intro.quantecon.org/finite_markov.html#Ergodicity: Anchor 'Ergodicity' not found
> about_py.md:477: [broken] https://www.dask.org/: 525 Server Error:  for url: https://www.dask.org/
> python_essentials.md:626: [redirected with Found] https://www.python.org/dev/peps/pep-0008/ to https://peps.python.org/pep-0008/
> ```
> 
> would you mind to look at those and fix them on this branch. Then I will reopen this PR and trigger another run of the link checker to see if it fails on `permanent redirects` also.

Hi @mmcky,

I have tried the test again, it does not fail on `permanent redirects`. Sorry that I made a lot of unnecessary changes. I thought we need to change all redirected links based on your examples until I found some of the redirected links do not need to be changed.

**Comment by HumphreyYang** [comment]
> Looking at the diff did you update the redirects as well?

I changed some of them, but not all as you can see from the test result.

**Comment by HumphreyYang** [comment]
> Looking at the diff did you update the redirects as well?

Hi @mmcky, I have reverted changes that are not necessary. I think the link checker is not failing redirected links.

Sorry for the misunderstanding before.

**Comment by mmcky** [comment]
thanks @HumphreyYang -- sorry I wasn't clear. We will want to update the redirects as well to reduce possible future failures. But I was interested to know if redirects cause CI to fail :-)

It's good to know that it will only fail on broken links.

**Pull request merged**
