### PR TITLE
small updates

### PR DESCRIPTION
**Pull request by jstac**

### CODE REVIEW

**Comment by mmcky** [comment]
@jstac we switched to `yfinance` a little while back because I thought `yahoo` was a bit unstable via `pandas datareader` https://github.com/QuantEcon/lecture-python-programming.myst/pull/133

**Comment by jstac** [comment]
Ah, I didn't mean to make any of those changes.  Somehow I ended up with an old version of the repo in this branch --- hence the failure to compile.

I'll close this and start again `:-(`

**Comment by mmcky** [comment]
ah - thanks @jstac -- it was probably a derivative of `master` -- sorry for that complication :-(

**Comment by jstac** [comment]
Yeah, I guess so.  My mistake, hopefully all good now.

**Pull request closed without merging**
