### PR TITLE
ENH: upgrade docker to include quantecon-book-theme==0.5.0 (search)

### PR DESCRIPTION
**Pull request by mmcky**
This PR upgrades to `quantecon-book-theme==0.5.0` to incorporate search via a new Docker Container `cuda-12.1.0-anaconda-2023-03-py310-b`

### CODE REVIEW

**Comment by mmcky** [comment]
@HengchengZhang in this PR the following link is `403`

```
(        about_py: line   85) broken    https://www.sciencedirect.com/science/article/pii/S1477388021000177 - 403 Client Error: Forbidden for url: https://www.sciencedirect.com/science/article/pii/S1477388021000177
```

is this the Wiley issue? Do we need to add sciendirect to the ignore list as well?

**Comment by mmcky** [comment]
- [ ] wait for minor fixes in `0.5.1` before deployment https://github.com/QuantEcon/quantecon-book-theme/issues/210

**Comment by HengchengZhang** [comment]
> https://www.sciencedirect.com/science/article/pii/S1477388021000177

Yes its the same issue with Wiley, but this link also failed in markdown link checker.

But the reason it fails in the md link checker is that there are invalid links in that page.

**Comment by mmcky** [comment]
Closing as waiting for `0.5.4` for theme.

**Pull request closed without merging**
