### PR TITLE
[pdflatex] Enable book style build of PDF via LaTeX

### PR DESCRIPTION
**Pull request by mmcky**
This PR brings book style PDF support via LaTeX

### CODE REVIEW

**Comment by mmcky** [comment]
@AakashGfude this doesn't seem to be picking up that there is a `pdf` available. How is the `name` of the file determined? I suspect i also need to update `_config.yml`

**Comment by mmcky** [comment]
This is presenting a settings button for the `live` build launcher. With one option it should just retain the single launch button. I think maybe my `_config` isn't setup correctly on this either?

Screen Shot 2021-05-06 at 10 57 02 am

**Comment by AakashGfude** [comment]
> This is presenting a settings button for the `live` build launcher. With one option it should just retain the single launch button. I think maybe my `_config` isn't setup correctly on this either?
> 
> Screen Shot 2021-05-06 at 10 57 02 am

Right @mmcky, we need to put only one launcher in `_config`. at present it has all of them https://github.com/QuantEcon/lecture-python-programming.myst/blob/master/lectures/_config.yml#L31

**Comment by AakashGfude** [comment]
> @AakashGfude this doesn't seem to be picking up that there is a `pdf` available. How is the `name` of the file determined? I suspect i also need to update `_config.yml`

It gets the name from the `latex_documents` key. 
The reason it is not detecting here is that I am checking for the presence of pdf before showing it. SInce latex is run after HTML in the ci. When building HTML, pdf is not present. 
What I did earlier in the test PR was to move the latex build before HTML. https://github.com/QuantEcon/lecture-python.myst/pull/127/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR31

**Comment by mmcky** [comment]
Hmm one interesting issue is the `cache` that I have on `github actions`. We may need a mechanism to rebuild `clean`

**Comment by mmcky** [comment]
thanks @AakashGfude this is looking nice. Could you take a look and let me know what you think. 

- [x] needs to be merged after #138

**Pull request merged**
