### PR TITLE
[UPDATE] Adding placeholder for google Analytics

### PR DESCRIPTION
**Pull request by AakashGfude**
**IMPORTANT** : put the analytics id of `lecture-python-programming` here before merging the PR.

Just a placeholder for the correct location of google analytics id

### CODE REVIEW

**Comment by mmcky** [comment]
ok great - so that `config` will just flow through to our `html` using `quantecon_book_theme`?

**Comment by AakashGfude** [comment]
> ok great - so that `config` will just flow through to our `html` using `quantecon_book_theme`?

That's right

**Comment by mmcky** [comment]
@AakashGfude and @DrDrij should this now be merged?

**Comment by AakashGfude** [comment]
@mmcky should be ready to merge now.

**Pull request merged**
