### PR TITLE
[TEST]:  Testing jupyter-book==0.15.1 (upcoming release)

### PR DESCRIPTION
**Pull request by AakashGfude**
Testing with Jupyter-book PR: https://github.com/executablebooks/jupyter-book/pull/1842

### CODE REVIEW

**Comment by mmcky** [comment]
@AakashGfude this looks pretty good to me. Some new styles I see for dropdowns coming through.

**Comment by AakashGfude** [comment]
Hi @mmcky it looks good to me as well. Although the 'View Source' link seems to be broken (which is probably not related to this PR). I will create an issue for that.

**Comment by mmcky** [comment]
> Hi @mmcky it looks good to me as well. Although the 'View Source' link seems to be broken (which is probably not related to this PR). I will create an issue for that.

Is this an issue on the current live site as well?

**Comment by mmcky** [comment]
- [x] check with `quantecon-book-theme`

**Comment by mmcky** [comment]
@HumphreyYang @shlff 

This is a build of the `python-programming` site using the latest and greatest `jupyter-book==0.15`. This is building with a new major version of `sphinx` so it would be really helpful if you could take a quick look around at the deployment preview and let me know if you spot any issues. 

https://63ce12b93d29576b04813b49--epic-agnesi-957267.netlify.app/intro.html

It looks pretty good to me. 

The things that aren't working for this build:

1. `pdf` builds
2. `download notebook` builds

**Comment by shlff** [comment]
Thanks @mmcky and @AakashGfude . There are two issues I've spotted so far.

The first is that there are some enormous space gaps between lines, like this:
Screenshot 2023-01-23 at 4 29 12 pm
This issue occurs in the following lectures:
- https://63ce12b93d29576b04813b49--epic-agnesi-957267.netlify.app/python_oop.html
- https://63ce12b93d29576b04813b49--epic-agnesi-957267.netlify.app/scipy.html
- https://63ce12b93d29576b04813b49--epic-agnesi-957267.netlify.app/parallelization.html
- https://63ce12b93d29576b04813b49--epic-agnesi-957267.netlify.app/writing_good_code.html

Another issue is that there are texts overlapped in the outputs in the lecture ``pandas``:
- https://63ce12b93d29576b04813b49--epic-agnesi-957267.netlify.app/pandas.html

like this:
Screenshot 2023-01-23 at 4 30 04 pm

**Comment by mmcky** [comment]
thanks @shlff this is really helpful.

**Comment by mmcky** [comment]
@AakashGfude the `pandas` output is concerning. Do you think this is a theme issue or it has changed due to the way `myst-nb` parses executable output?

**Comment by HumphreyYang** [comment]
> Thanks @mmcky and @AakashGfude . There are two issues I've spotted so far.
> 
> The first is that there are some enormous space gaps between lines, like this: 

I also noticed this, and I found it relates to the in-text math symbols we use. Also see here: 
https://63ce12b93d29576b04813b49--epic-agnesi-957267.netlify.app/getting_started.html#inserting-unicode-e-g-greek-letters

**Comment by HumphreyYang** [comment]
> > Thanks @mmcky and @AakashGfude . There are two issues I've spotted so far.
> > The first is that there are some enormous space gaps between lines, like this:
> 
> I also noticed this, and I found it relates to the in-text math symbols we use. Also see here: https://63ce12b93d29576b04813b49--epic-agnesi-957267.netlify.app/getting_started.html#inserting-unicode-e-g-greek-letters

Many thanks @AakashGfude  @mmcky  @shlff. I am not sure if it is intended, but the graphs generated by code [now](https://python-programming.quantecon.org/numba.html) are larger than the [past versions](https://6308a78b359bf502450d07ad--epic-agnesi-957267.netlify.app/numba.html), and the shape is varying instead of having the same aspect ratio as they used to be. See another example here: [versions now](https://python-programming.quantecon.org/pandas.html#on-line-data-sources) compared to [older versions](https://6308a78b359bf502450d07ad--epic-agnesi-957267.netlify.app/pandas.html#on-line-data-sources).

**Comment by mmcky** [comment]
> I also noticed this, and I found it relates to the in-text math symbols we use. Also see here:
https://63ce12b93d29576b04813b49--epic-agnesi-957267.netlify.app/getting_started.html#inserting-unicode-e-g-greek-letters

@HumphreyYang are you saying the the additional spaces are only when we use greek unicode letters?

**Comment by mmcky** [comment]
@shlff 

it looks like

> https://63ce12b93d29576b04813b49--epic-agnesi-957267.netlify.app/python_oop.html

is resolved in `sphinx-book-theme`

https://63cf4ba2a0f50b6ae322413f--epic-agnesi-957267.netlify.app/python_oop.html#special-methods

@AakashGfude it looks like there must be some style inheritance issues in `quantecon-book-theme`

**Comment by mmcky** [comment]
@shlff the pandas issue also looks resolved when using `sphinx-book-theme`

https://63cf4ba2a0f50b6ae322413f--epic-agnesi-957267.netlify.app/pandas.html#dataframes

**Comment by mmcky** [comment]
> I am not sure if it is intended, but the graphs generated by code [now](https://python-programming.quantecon.org/numba.html) are larger than the [past versions](https://6308a78b359bf502450d07ad--epic-agnesi-957267.netlify.app/numba.html), and the shape is varying instead of having the same aspect ratio as they used to be. See another example here: [versions now](https://python-programming.quantecon.org/pandas.html#on-line-data-sources) compared to [older versions](https://6308a78b359bf502450d07ad--epic-agnesi-957267.netlify.app/pandas.html#on-line-data-sources).

Thanks @HumphreyYang I agree -- this has also changed in `sphinx-book-theme` it seems so there must be a change with regards to `fig size` imports. I will check with the `Jupyter Book` team. 

**Edit:** @HumphreyYang it actually looks like many figures are a bit smaller now than in the current live site. Is that what you are seeing?

**Comment by HumphreyYang** [comment]
> > I am not sure if it is intended, but the graphs generated by code [now](https://python-programming.quantecon.org/numba.html) are larger than the [past versions](https://6308a78b359bf502450d07ad--epic-agnesi-957267.netlify.app/numba.html), and the shape is varying instead of having the same aspect ratio as they used to be. See another example here: [versions now](https://python-programming.quantecon.org/pandas.html#on-line-data-sources) compared to [older versions](https://6308a78b359bf502450d07ad--epic-agnesi-957267.netlify.app/pandas.html#on-line-data-sources).
> 
> **Edit:** @HumphreyYang it actually looks like many figures are a bit smaller now than in the current live site. Is that what you are seeing?


I think they are larger actually:
**Edit**:  @mmcky The link I attached is a very old preview dating back to when I contributed to the `matplotlib` lecture last year.

Old: 
Screenshot 2023-01-24 at 22 09 16

New: 
Screenshot 2023-01-24 at 22 09 08

They are screenshots within the same window.

**Comment by HumphreyYang** [comment]
> > I also noticed this, and I found it relates to the in-text math symbols we use. Also see here:
> > https://63ce12b93d29576b04813b49--epic-agnesi-957267.netlify.app/getting_started.html#inserting-unicode-e-g-greek-letters
> 
> @HumphreyYang are you saying the the additional spaces are only when we use greek unicode letters?

I am not sure if it is related to `$` or unicode letters but it appears to me that the gaps appear when we use  `$$` in text.

**Comment by mmcky** [comment]
@HumphreyYang and @shlff thanks for your reviews. It looks like we will need to make changes to the `quantecon-book-theme` before we deploy the latest `jupyterbook` but all of the pickups seem to be resolved when using `sphinx-book-theme`

cc: @AakashGfude

**Comment by AakashGfude** [comment]
@HumphreyYang @shlff @mmcky, the table seems to be working fine here: https://63ce12b93d29576b04813b49--epic-agnesi-957267.netlify.app/pandas.html , apart from a minor overlap in the entries.
Screen Shot 2023-02-09 at 2 59 57 pm

which is taken care of in sphinx-book-theme, so probably would just inherit its style.

**Comment by AakashGfude** [comment]
fixed in this commit https://github.com/QuantEcon/quantecon-book-theme/pull/186/commits/be517c53fae3d81575755279c0739d43cd3dbb3e, the table issue. 
Screen Shot 2023-02-09 at 4 12 29 pm

**Comment by mmcky** [comment]
thanks @shlff @HumphreyYang @AakashGfude for your input into this testing campaign. This is now building on the latest jupyterbook and quantecon-book-theme and looking pretty good. 

- [x] table rendering is fixed https://641799b601f1ec2effb07975--epic-agnesi-957267.netlify.app/pandas.html

some of the images might still be a bit larger but we can iterate through the lectures at some point and review them.

**Comment by mmcky** [comment]
Closed by #267

**Pull request closed without merging**
