### PR TITLE
Chapter 1 Review: update hyperlinks and outdated packages

### PR DESCRIPTION
**Pull request by HumphreyYang**
Hi,

I have looked through the first chapter (About Python) of the lecture and found several outdated links.

Other than these, the only fix is a warning from iPython at line 324 due to a formatting issue.

Since this is a short chapter without too many changes made, so I put everything in one PR. Please kindly review the changes.

Thank you.

### CODE REVIEW

**Comment by jstac** [comment]
Great work @HumphreyYang , many thanks.  This is very helpful!

Would you mind also reviewing the links to determine whether or not they are as up to date as possible?

For example, we cite Theano for GPUs but I don't think it's very popular any more.  (I could be wrong but it seems to have been overtaken by JAX.)

I feel like we should at least mention JAX and PyTorch.  

This is a harder task, but perhaps you could make one or two small changes along these lines as well?

**Comment by jstac** [comment]
This is great, thanks @HumphreyYang .

Ready for us to merge once the checks have passed?

**Comment by HumphreyYang** [comment]
Hi John,

I have just added some more on the recent development on HPC.

Here is a summary of what I have done in the latest commits:

1. Added more recent packages in graphics, statistics, cloud computing, and high-performance computing (HPC);
2. Provided more resources on data science and HPC;
3. In the example section for Scipy, the book mentioned integral calculation, but there is no example for the ```integrate()``` method below. Thus, I added an example, a slightly complicated integral, in that section.

Please kindly check these recent updates, and leave a comment if there is anything more you would like me to add.

If everything looks good to you, please merge them whenever you think appropriate.

Thank you.

**Comment by mmcky** [comment]
thanks @HumphreyYang this is a nice update for the lecture.

**Comment by jstac** [comment]
Many thanks @HumphreyYang .

I think there are a few more changes we could make.  For example,

* the [Walt Disney Animation](https://pydanny-event-notes.readthedocs.org/en/latest/socalpiggies/20110526-wda.html) link is old and can be deleted
* Instead of that one, we could add Amazon and Facebook/Meta as companies actively using Python
* The link in "Python is very beginner-friendly and is often used to [teach computer science and programming](http://cacm.acm.org/blogs/blog-cacm/176450-python-is-now-the-most-popular-introductory-teaching-language-at-top-us-universities/fulltext)" is very old --- is there a newer one we could use?
* Is VPython still popular?  I clicked on the link and it looks old and unimpressive.  Can you suggest a replacement?  Maybe seaborn?
* I think PyMC is pretty old too.  Should we replace that link?  Please see https://stackoverflow.com/questions/48334627/pyro-vs-pymc-what-are-the-difference-between-these-probabilistic-programming-fr
* The SageMath Cloud link seems outdated --- maybe just delete this?
* Google App Engine should perhaps be replaced by Google colab
*

**Comment by HumphreyYang** [comment]
Hi John,

I think I have changed several points you mentioned in the latest deployment such as on
Seaborn and SageMath. But I will definitely review everything again and update the contents more aggressively.

Thank you so much for your feedback.

**Comment by jstac** [comment]
@HumphreyYang , sorry I missed those changes but yes please, one more round would be great.

**Comment by HumphreyYang** [comment]
Hi @jstac and @mmcky,

Thank you so much for your feedback in the previous round. I started to grasp the required level of revision for the lectures.

In this round of revision, I incorporated the list of suggestions by @jstac and added more resources on the application of Python and libraries. I checked all listed libraries and made sure there are recent discussions on the library on StackOverflow.

The only suggestion that I failed to incorporate into this version is:

- [ ] The link in "Python is very beginner-friendly and is often used to [teach computer science and programming](http://cacm.acm.org/blogs/blog-cacm/176450-python-is-now-the-most-popular-introductory-teaching-language-at-top-us-universities/fulltext)" is very old --- is there a newer one we could use?

Although I failed to find solid support for Python as the most popular first language at the university level (a 2016 study in the UK is even against this statement), I did find many case studies on Python for students from non-CS backgrounds that demonstrate key advantages of Python.

Could you please kindly visit the latest employment and review these changes?


Many thanks.

**Comment by jstac** [comment]
Hi @HumphreyYang , I've looked over this carefully and you've done a great job.  I'm really happy to see this page up to date again!  I'll go ahead and merge now.

**Pull request merged**
