### PR TITLE
Chapter 3 Review: Add Explanations and Address Exercise Issue

### PR DESCRIPTION
**Pull request by HumphreyYang**
Hi @jstac and @mmcky,

I have finished the review of Chapter 3. The following changes have been made:

1. Added explanations for while loop and solution for exercise 5;
2. Added a line of code to find the location of the library in Python;
3. addressed #192 in Chapter 3.

Could you please kindly review the changes and provide some feedback on the changes?

Thank you.

### CODE REVIEW

**Comment by jstac** [comment]
Hi @HumphreyYang , thanks for these changes and suggestions.

Do you have time to chat quickly about this?  If so please email me a google meet or zoom invitation.

**Comment by HumphreyYang** [comment]
Hi @jstac,

Thank you for your kind comment. I have simplified the previous version and corrected the comment in the exercise. 

Could you please kindly review this version and merge it whenever you find it appropriate?

**Comment by jstac** [comment]
Great work @HumphreyYang .

Sorry for the bother but could you please also 

1. delete the sentence "In fact, you can find and explore the directory for NumPy on your computer easily enough if you look around."  I think it's now redundant, given your addition.
2. change "We’ll learn all about methods later on in [Object Oriented Programming](link)..." to "We'll learn all about methods [later on](link)..."

After that I'll merge.

**Comment by HumphreyYang** [comment]
Hi @jstac,

Thank you for your comment. I have updated the page accordingly, and I will try to be more concise in the future.

Please kindly merge if you think it looks good to you now.

Thank you.

**Comment by jstac** [comment]
Hmmm, it doesn't look like the last changes went through when I click on the "Deployed on" link above

https://62e9f3f85edd124d6f813070--epic-agnesi-957267.netlify.app/python_by_example.html

**Comment by HumphreyYang** [comment]
Hi @jstac,

The latest deployment is associated with [this commit](https://github.com/QuantEcon/lecture-python-programming.myst/commit/42e12f668c75dc2d1dc029738fcab3b44d60f04a#comments), and the link to the deployment is [here](https://62e9ee2e938189496d340380--epic-agnesi-957267.netlify.app/). All changes have been reflected in the latest deployment.

The deployment you shared (https://62e9f3f85edd124d6f813070--epic-agnesi-957267.netlify.app/) is associated with [a commit two days ago](https://github.com/QuantEcon/lecture-python-programming.myst/commit/5a28d48148c268165e690e9f455877703dc2a648#comments), which is outdated.

I am not sure why the sequence of deployment is reversed on this page, but on the commit page, it seems to be correct.

**Comment by jstac** [comment]
Perfect, thanks @HumphreyYang .   Nice work.

I'll go ahead and merge.  

Can you please open an issue stating that all exercise / solution groups should be modified to the format used here?

**Pull request merged**
