### PR TITLE
[Migration] Manual Infrastructure adjustments for Migration of Lecture Series

### PR DESCRIPTION
**Pull request by mmcky**
This PR contains manual adjustments needed to migrate this project:

**Currently:** this moves `md` files but doesn't change any `md` files. This should be done as a second PR. 

- [x] migrate to using `quantecon_book_theme`
- [x] remove top level landing/title page and replace with table of contents page (formerly `index_toc`)

Manual Adjustments

- [ ] add `_config.yml` and `_toc.yml` for builds with `jupyter-book` (Current test PR #53)

Combining #38 and #32 to get a full view of the resulting `html`

### CODE REVIEW

**Comment by mmcky** [comment]
@AakashGfude please review your changes -- build is failing.

**Comment by AakashGfude** [comment]
@mmcky weird. the build seems to be using an old code of `quantecon-book-theme` .

**Comment by AakashGfude** [comment]
aah, the CI downloads `quantecon-book-theme` from the `qe-theme` branch. which has old code

**Comment by mmcky** [comment]
Closing this in favour of `jupyter-book` build PR #53

**Pull request closed without merging**
