### PR TITLE
[pandas] index already in datetime

### PR DESCRIPTION
**Pull request by mmcky**

### CODE REVIEW

**Comment by mmcky** [comment]
@HumphreyYang I will merge this to fix the cache but it looks like PetroChina is no longer a valid ticker in the exercise.

**Comment by HumphreyYang** [comment]
Hi @mmcky,

```
# Change the index to date
prices.index = pd.to_datetime(prices.index.date)
```

This line is needed for Nikkei data to show up. I think the problem in the cache run is caused by missing values in PetroChina.

**Comment by HumphreyYang** [comment]
Hi @mmcky, I am fixing this issue in #252.

**Comment by mmcky** [comment]
> Hi @mmcky,
> 
> ```
> # Change the index to date
> prices.index = pd.to_datetime(prices.index.date)
> ```
> 
> This line is needed for Nikkei data to show up. I think the problem in the cache run is caused by missing values in PetroChina.

The issue when I looked at it though is with `prices.index.date` the index didn't contain a `date` named parameter.

**Comment by HumphreyYang** [comment]
> > Hi @mmcky,
> 
> > 
> 
> > ```
> 
> > # Change the index to date
> 
> > prices.index = pd.to_datetime(prices.index.date)
> 
> > ```
> 
> > 
> 
> > This line is needed for Nikkei data to show up. I think the problem in the cache run is caused by missing values in PetroChina.
> 
> 
> 
> The issue when I looked at it though is with `prices.index.date` the index didn't contain a `date` named parameter. 

I saw that as well. It seems 'yfinance' does not return 'datetime' when the ticker is not found.

**Pull request merged**
