### PR TITLE
[pandas] small updates

### PR DESCRIPTION
**Pull request by jstac**

### CODE REVIEW

**Comment by jstac** [comment]
@mmcky , the figure near the top on popularity of pandas is too small.  What's the approved way to resize this?

Thanks.

**Comment by mmcky** [comment]
@jstac currently it is sized at 40%

````
```{figure} /_static/lecture_specific/pandas/pandas_vs_rest.png
:scale: 40
```
````

so we can just relax that resizing?

**Comment by jstac** [comment]
Sorry Matt, I'm tired and trying to do too many things at once.  Thanks for your patience `:-)`

**Comment by mmcky** [comment]
> Sorry Matt, I'm tired and trying to do too many things at once. Thanks for your patience `:-)`

Absolutely no worries. It's nice knowing a few things about `MyST` and being able to help out `:-)`

**Comment by mmcky** [comment]
@jstac you can also use `align` if you want it to be centered etc.

https://jupyterbook.org/content/figures.html?highlight=figurs#figure-scaling-and-aligning

but that should be default so not sure why it wasn't showing centered.

**Comment by mmcky** [comment]
https://github.com/QuantEcon/quantecon-book-theme/issues/164

**Comment by jstac** [comment]
It looks fine.  Thanks again @mmcky

**Pull request merged**
