### PR TITLE
ENH: Upgrade quantecon-book-theme==0.7.0

### PR DESCRIPTION
**Pull request by mmcky**
This PR upgrades `quantecon-book-theme==0.7.0` which gives us:

1. author control on main page (including links)
2. newly enabled `margin` notes support

### CODE REVIEW

**Comment by mmcky** [comment]
@jstac -- we now have the ability to place author information on the front page and control the font size via `_config.yml` (thanks @AakashGfude). These are now also clickable links that can take you to an author page etc. 

https://657935bc66c8e751b11f8a41--epic-agnesi-957267.netlify.app/intro.html

@HumphreyYang we will be able to use the latest release theme to add in the author information for the new `lecture `repositories.

**Comment by HumphreyYang** [comment]
> @jstac -- we now have the ability to place author information on the front page and control the font size via `_config.yml` (thanks @AakashGfude). These are now also clickable links that can take you to an author page etc.
> 
> https://657935bc66c8e751b11f8a41--epic-agnesi-957267.netlify.app/intro.html
> 
> @HumphreyYang we will be able to use the latest release theme to add in the author information for the new `lecture `repositories.

Many thanks @mmcky and @AakashGfude. I will test them out once it is released.

**Comment by mmcky** [comment]
> Many thanks @mmcky and @AakashGfude. I will test them out once it is released.

@HumphreyYang it has been released to `PyPI` and is `v0.7.0`

You will need to add the following to the `_config.yml`

```
      authors:  
         - name: Thomas J. Sargent
           url: http://www.tomsargent.com/
         - name: John Stachurski
           url: https://johnstachurski.net/
```

under `html_theme_options`

See https://github.com/QuantEcon/lecture-python-programming.myst/pull/299/files for reference. 

Let me know if you'd prefer I add this information to the source repositories or target the new lecture repositories with additional config.

**Comment by HumphreyYang** [comment]
> Let me know if you'd prefer I add this information to the source repositories or target the new lecture repositories with additional config.

Many thanks @mmcky, please keep the old repositories if possible as it is as I have updated the mapping code to incorporate these changes : )

**Comment by HumphreyYang** [comment]
> > Let me know if you'd prefer I add this information to the source repositories or target the new lecture repositories with additional config.
> 
> Many thanks @mmcky, please keep the old repositories if possible as it is as I have updated the mapping code to incorporate these changes : )

Please find one of the output here:
https://quantecon.github.io/lecture-dle/intro.html

**Comment by mmcky** [comment]
Closing as not required. The new lecture series will incorporate the latest theme.

**Pull request closed without merging**
