### PR TITLE
MAINT: upgrade latest build software versions

### PR DESCRIPTION
**Pull request by mmcky**
This upgrades the software to the latest versions of `jupyter-book` including updates to `quantecon-book-theme` and `sphinx-exercise` for compatibility. 

- [x] release `quantecon-book-theme==0.7.5` once bugs fixed
- [x] release `sphinx-exercise==1.0.1` once bugs fixed
- [x] review preview to check outputs using latest `jupyter-book==1.0.3`

### CODE REVIEW

**Comment by mmcky** [comment]
Current issues with theme

## Title Page

- [x] missing theme formatting line under Title
- [x] missing the quantecon logo
- [x] missing Authors information

Current Preview

Screenshot 2024-10-25 at 6 00 59 pm


Current Live Site

Screenshot 2024-10-25 at 6 01 09 pm

**Comment by mmcky** [comment]
@DrDrij it looks like the variable names may have changed as we upgraded to `jupyter-book<1.0` -- as the `theme_authors` variable in our `quantecon_book_theme` layout.html file is no longer filling in this section https://github.com/QuantEcon/quantecon-book-theme/blob/90fba30c2c4d7743333c9567bb8ac82b29871c36/src/quantecon_book_theme/theme/quantecon_book_theme/layout.html#L152

any ideas?

**Comment by DrDrij** [comment]
That's no good. Perhaps we hard code them temporarily? 
I will examine further tomorrow afternoon @mmcky

**Comment by agoose77** [comment]
FWIW I'm seeing this: 
image

```txt
accessible-pygments==0.0.5
alabaster==0.7.16
anyio==4.6.2.post1
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array_to_latex==0.92
arrow==1.3.0
asttokens==2.4.1
attrs==24.2.0
babel==2.16.0
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
click==8.1.7
clipboard==0.0.4
cloudpickle==3.1.0
colorama==0.4.6
comm==0.2.2
contourpy==1.3.0
cycler==0.12.1
dask==2024.10.0
debugpy==1.8.7
decorator==5.1.1
defusedxml==0.7.1
distributed==2024.10.0
docutils==0.17.1
executing==2.1.0
fastjsonschema==2.20.0
fonttools==4.54.1
fqdn==1.5.1
frozendict==2.4.6
fsspec==2024.10.0
ghp-import==1.1.0
gitdb==4.0.11
GitPython==3.1.43
greenlet==3.1.1
html5lib==1.1
idna==3.10
imagesize==1.4.1
importlib_metadata==8.5.0
ipykernel==6.29.5
ipython==8.29.0
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.4
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
jupyter-book==0.15.1
jupyter-cache==0.6.1
jupyter-events==0.10.0
jupyter-server-mathjax==0.2.6
jupyter_client==8.6.3
jupyter_core==5.7.2
jupyter_server==2.14.2
jupyter_server_terminals==0.5.3
jupyterlab_pygments==0.3.0
kiwisolver==1.4.7
latexcodec==3.0.0
libsass==0.20.1
linkify-it-py==2.0.3
llvmlite==0.43.0
locket==1.0.0
lxml==5.3.0
markdown-it-py==2.2.0
MarkupSafe==3.0.2
matplotlib==3.9.2
matplotlib-inline==0.1.7
mdit-py-plugins==0.3.5
mdurl==0.1.2
mistune==3.0.2
mpmath==1.3.0
msgpack==1.1.0
multitasking==0.0.11
myst-nb==0.17.2
myst-parser==0.18.1
nbclient==0.7.4
nbconvert==7.16.4
nbdime==4.0.2
nbformat==5.10.4
nest-asyncio==1.6.0
numba==0.60.0
numpy==2.0.2
overrides==7.7.0
packaging==24.1
pandas==2.2.3
pandas-datareader==0.10.0
pandocfilters==1.5.1
parso==0.8.4
partd==1.4.2
peewee==3.17.7
pexpect==4.9.0
pillow==11.0.0
platformdirs==4.3.6
prettytable==3.11.0
prometheus_client==0.21.0
prompt_toolkit==3.0.48
psutil==6.1.0
ptyprocess==0.7.0
pure_eval==0.2.3
pybtex==0.24.0
pybtex-docutils==1.0.3
pycparser==2.22
pydata-sphinx-theme==0.15.4
Pygments==2.18.0
pyparsing==3.2.0
pyperclip==1.9.0
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
pytz==2024.2
PyYAML==6.0.2
pyzmq==26.2.0
quantecon==0.7.2
quantecon-book-theme==0.7.2
referencing==0.35.1
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.9.3
rpds-py==0.20.0
scipy==1.14.1
seaborn==0.13.2
Send2Trash==1.8.3
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soupsieve==2.6
Sphinx==5.0.2
sphinx-book-theme==1.0.1
sphinx-comments==0.0.3
sphinx-copybutton==0.5.2
sphinx-exercise==0.4.1
sphinx-jupyterbook-latex==0.5.2
sphinx-multitoc-numbering==0.1.3
sphinx-thebe==0.2.1
sphinx-togglebutton==0.3.1
sphinx-tojupyter==0.3.0
sphinx_design==0.3.0
sphinx_external_toc==0.3.1
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-bibtex==2.5.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
sphinxcontrib-youtube==1.1.0
sphinxext-rediraffe==0.2.7
SQLAlchemy==2.0.36
stack-data==0.6.3
sympy==1.13.3
tabulate==0.9.0
tblib==3.0.0
terminado==0.18.1
tinycss2==1.4.0
toolz==1.0.0
tornado==6.4.1
traitlets==5.14.3
types-python-dateutil==2.9.0.20241003
typing_extensions==4.12.2
tzdata==2024.2
uc-micro-py==1.0.3
uri-template==1.3.0
urllib3==2.2.3
wcwidth==0.2.13
webcolors==24.8.0
webencodings==0.5.1
websocket-client==1.8.0
yfinance==0.2.48
zict==3.0.0
zipp==3.20.2
```

**Comment by mmcky** [comment]
thanks @DrDrij just not sure how the templates actually get rendered.

**Comment by mmcky** [comment]
@DrDrij the interesting part is that the `html` is still there

```html
                        <p class="qe-page__header-authors" font-size="18">
                            
                                
                                    <a href="http://www.tomsargent.com/" target="_blank"><span>Thomas J. Sargent</span></a>
                                
                            
                                
                                    and <a href="https://johnstachurski.net/" target="_blank"><span>John Stachurski</span></a>
                                
                            
                        </p>
```

but it just isn't showing up on the rendered page

**Comment by mmcky** [comment]
however in the case of the `logo` the `html` is missing

The live site has

```html
                            <p class="logo">
                                
                                    
                                    <a href=https://quantecon.org><img src="_static/qe-logo.png" class="logo logo-img" alt="logo"></a>
                                    
                                    <a href=https://quantecon.org><img src="_static/quantecon-logo-transparent.png" class="dark-logo-img" alt="logo"></a>
                                    
                                    
                                
                            </p>

                            <p class="powered">Powered by <a href="https://jupyterbook.org/">Jupyter Book</a></p>
```

while this preview build has

```html
                            
                            <p class="logo">
                                
                            </p>

                            <p class="powered">Powered by <a href="https://jupyterbook.org/">Jupyter Book</a></p>

```

**Comment by DrDrij** [comment]
Looks like authors is printed out in 2 places, the first instance shows on all other pages except 'main-index':
 (https://github.com/QuantEcon/quantecon-book-theme/blob/90fba30c2c4d7743333c9567bb8ac82b29871c36/src/quantecon_book_theme/theme/quantecon_book_theme/layout.html#L152)

image


And the second is appearing in the content area, after the Heading 1 element, so in the content block: (https://github.com/QuantEcon/quantecon-book-theme/blob/90fba30c2c4d7743333c9567bb8ac82b29871c36/src/quantecon_book_theme/theme/quantecon_book_theme/layout.html#L175C30-L175C39)

image

So it means we've lost the author header printing out in the `{% block body %} {% endblock %}` include.

On further inspection, I see that the theme uses Javascript to move the authors on the homepage to sit in the right place under the Heading 1 (https://github.com/QuantEcon/quantecon-book-theme/blob/90fba30c2c4d7743333c9567bb8ac82b29871c36/src/quantecon_book_theme/assets/scripts/index.js#L380).

How many years ago did I write this? 🙈

So JS is broken somewhere — try to open the left menu or use any of the theme toolbar buttons around the page.

The console gives a little details which indicates we have lost jQuery.

image

It appears that https://671b40f5a93d541ba1e37280--epic-agnesi-957267.netlify.app/_static/scripts/sphinx-book-theme.js isn't loading (404). Has that changed with the new version @mmcky ?

Hope this gives some clue. I can investigate further, interested in your thoughts?

**Comment by agoose77** [comment]
@DrDrij @mmcky I'm having conversations in two places! I'll move the chat here.

@DrDrij yes, Sphinx 6 dropped JQuery. The easiest fix is to bundle it with webpack by adding it to your dependencies, importing it in your JS file, and setting `noconflict` mode.

As for the SBT -- I wonder whether you really should only inherit from pydata-sphinx-theme, as that is where most/all of the accessibility etc features are.

**Comment by mmcky** [comment]
thanks @DrDrij and @agoose77. 

@DrDrij we will need to add in jQuery to get this to work for now. 

@agoose77 I agree that we should be inheriting from pydata-sphinx-theme. With our planned upcoming migration to `mystmd` I am just focused on the essentials to get this working with the latest `jupyter-book` so we can freeze this theme at that point in time.

**Comment by mmcky** [comment]
@DrDrij @agoose77 thanks again for your help here. 

I have pinned quantecon-book-theme to use `sphinx>=5,<6` for now and is building this PR with the elements we expect to be in place. 

I have opened https://github.com/QuantEcon/quantecon-book-theme/issues/274 to see if we can fix the jQuery issue and remove this pin. But happy with this solution for now given the upcoming switch to `mystmd`

**Comment by mmcky** [comment]
- [ ] @mmcky working on making QuantEcon workflows shared and centralised.

**Comment by mmcky** [comment]
@HumphreyYang this PR makes major upgrades to our `jupyter-book` infrastructure to use `jb==1.0.3` and all associated packages I have updated last week including `sphinx-exercise`, `sphinx-proof` for compatibility. 

I have done a pretty good review and check but if you have time to cast your eye over this preview to see if you spot any regressions that would be super helpful. 

https://674a6757a64b3c66ca69bb11--epic-agnesi-957267.netlify.app/

**Comment by HumphreyYang** [comment]
Many thanks @mmcky. I did not spot any issue! 

I think we did not use proof env in this repo so perhaps I can have another look in the undergraduate series once this change is implemented over there?

**Comment by mmcky** [comment]
thanks @HumphreyYang

**Pull request merged**
