### PR TITLE
[python_by_example] Remove the unnecessary text for matplotlib inline

### LINKED ISSUE #271: Python by example lecture
I think we can drop this now?

```
We run the following command first, which helps ensure that plots appear in the notebook if you run it on your own machine.

%matplotlib inline
```

### PR DESCRIPTION
**Pull request by HengchengZhang**
Hi @jstac and @mmcky, this PR fix #271.

I've tested it in my local environment and it looks well after deleting the text.

### CODE REVIEW

**Comment by jstac** [comment]
Nice work @HengchengZhang , many thanks. 

Please fix the failing build or ping @mmcky  if you're not sure what's happening.

**Comment by mmcky** [comment]
@HengchengZhang would you mind to review the links that are reported as broken such as

```
(        about_py: line   85) broken    https://www.sciencedirect.com/science/article/pii/S1477388021000177 - 403 Client Error: Forbidden for url: https://www.sciencedirect.com/science/article/pii/S1477388021000177
```

there are a couple of additional ones in the GitHub actions output for the `Link Checker`

https://github.com/QuantEcon/lecture-python-programming.myst/actions/runs/4663763516/jobs/8255387311?pr=272

**Comment by HengchengZhang** [comment]
Thanks @jstac and @mmcky, I checked these this afternoon but I think the broken links it gives all work actually.

**Comment by mmcky** [comment]
Roger that - the false positives are annoying with the link checker. We may need to think about seeing if there are some checks we can skip to reduce the false positivity rate at some point.

**Pull request merged**
