### PR TITLE
MIGRATE: pandas_panel lecture from stats

### LINKED ISSUE #303: Migrate `pandas_panel` to this lecture series
thanks @jstac -- we can migrate it. 

- [ ] migrate `pandas_panel` to python-programming lecture series.

_Originally posted by @mmcky in https://github.com/QuantEcon/lecture-stats/issues/21#issuecomment-1965630172_

### PR DESCRIPTION
**Pull request by mmcky**
This PR migrates `pandas_panel` from `lecture-stats`

fixes https://github.com/QuantEcon/lecture-python-programming.myst/issues/303

### CODE REVIEW

**Comment by mmcky** [comment]
There are a few deprecation notices that should be addressed

- [x] fix dataframe deprecation

```
FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  merged.groupby(level='Continent', axis=1).mean().head()
```

- [x] fix seaborn deprecation

```
/home/runner/miniconda3/envs/quantecon/lib/python3.11/site-packages/seaborn/_oldcore.py:1119: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
```

**Review by mmcky — COMMENTED** [review]
@jstac are you happy for this to be merged. 

The main changes to the incoming lecture are captured in https://github.com/QuantEcon/lecture-python-programming.myst/pull/310/commits/caaacae06957e7d4eb3b7b02bbad6878e8894171

**Comment by jstac** [comment]
Thanks @mmcky .   I'm a little busy but perhaps @shlff could provide a second set of eyes?

I'll leave you to merge when ready.

**Comment by mmcky** [comment]
Thanks @shlff the only real changes being applied are to fix deprecation notices in `pandas` in https://github.com/QuantEcon/lecture-python-programming.myst/commit/caaacae06957e7d4eb3b7b02bbad6878e8894171 otherwise this is just migrating the lecture from it's old location.

**Comment by shlff** [comment]
I see. Thanks @mmcky . 

I quickly went through the lecture: 
- the two depreciation notices have been fixed, and 
- all links are working well.

This lecture looks good to me so I reckon it is ready to be merged.

**Comment by mmcky** [comment]
thanks @shlff -- greatly appreciate the second set of eyes.

**Pull request merged**
