### PR TITLE
Chapter 14: Add Example and Fix Index

### PR DESCRIPTION
**Pull request by HumphreyYang**
Hi @jstac and @mmcky,

I ran through the Pandas lecture again and implemented the following changes to improve the previous revision:

1. Add an example for the `.applymap` method to enhance the logical flow of the lecture;
2. The numbering for the index appears to be restarting after the code block. This PR fixes this issue.

Could you please kindly review these changes and merge/deploy them if you find them useful?

Thank you so much for your time.

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @HumphreyYang this looks good to me (based on the source edits)

Not sure why netlify isn't showing a preview for this. It's on a local branch right?

**Comment by HumphreyYang** [comment]
> thanks @HumphreyYang this looks good to me (based on the source edits)
> 
> 
> 
> Not sure why netlify isn't showing a preview for this. It's on a local branch right?

Hi @mmcky 

Yes, it is in branch pandas_index_fix.

From what I can see in my last commit, it is deployed [here](https://62f9dcce86c9c20a142915f2--epic-agnesi-957267.netlify.app/intro.html)

I can see changes have been reflected in this deployment.

**Comment by mmcky** [comment]
@HumphreyYang the `!` is a command that runs something on the command line (in a temporary shell) and returns the result. Are you saying this has been deprecated? Or is it just that `%pip` is the recommended way to install using a new pip magic command?

**Comment by mmcky** [comment]
> > thanks @HumphreyYang this looks good to me (based on the source edits)
> > Not sure why netlify isn't showing a preview for this. It's on a local branch right?
> 
> Hi @mmcky
> 
> From what I can see in my last commit, it is deployed [here](https://62f9dcce86c9c20a142915f2--epic-agnesi-957267.netlify.app/intro.html)
> 
> I can see changes have been shown in this deployment.

thanks @HumphreyYang usually it posts a link.

**Comment by HumphreyYang** [comment]
> @HumphreyYang the `!` is a command that runs something on the command line and returns the result. Are you saying this has been deprecated? Or is it just that `%pip` is the recommended way to install using a new pip magic command?

@mmcky On the [Ipython documentation](https://ipython.readthedocs.io/en/stable/interactive/magics.html), it has been replaced by %, but on stackoverflow, some people indicated that it is still supported despite of having no documentation on it.

**Comment by mmcky** [comment]
> > @HumphreyYang the `!` is a command that runs something on the command line and returns the result. Are you saying this has been deprecated? Or is it just that `%pip` is the recommended way to install using a new pip magic command?
> 
> @mmcky From the [Ipython documentation](https://ipython.readthedocs.io/en/stable/interactive/magics.html) it has been replaced by %, but on stackoverflow, some people indicated that it is still supported despite there is no documentation on it.

Interesting it is in the [shell & directory management section](https://ipython.readthedocs.io/en/stable/interactive/shell.html#directory-management) but it does seem that `%pip` may be preferred. The `!` command runs in a temporary shell and then exits so things like `cd` don't work.

**Comment by HumphreyYang** [comment]
> > > @HumphreyYang the `!` is a command that runs something on the command line and returns the result. Are you saying this has been deprecated? Or is it just that `%pip` is the recommended way to install using a new pip magic command?
> > 
> > 
> > @mmcky From the [Ipython documentation](https://ipython.readthedocs.io/en/stable/interactive/magics.html) it has been replaced by %, but on stackoverflow, some people indicated that it is still supported despite there is no documentation on it.
> 
> Interesting it is in the [shell & directory management section](https://ipython.readthedocs.io/en/stable/interactive/shell.html#directory-management) but it does seem that `%pip` may be preferred. The `!` command runs in a temporary shell and then exits so things like `cd` don't work.

In that case, I will change it back to `!`. Thanks for letting me know that.

**Comment by HumphreyYang** [comment]
Hi @mmcky,

I have changed `%` back to `!`. Please kindly review the commit and merge this PR if you think it looks good to you.

Thank you.

**Comment by mmcky** [comment]
thanks @HumphreyYang

**Pull request merged**
