### PR TITLE
✨ NEW: Adding plugins config

### PR DESCRIPTION
**Pull request by AakashGfude**
@mmcky you think adding menubar like this will be a nice temporary solution?
using a `plugins_list` config variable and passing the js file of the plugin to it. Then loading the whole js in the template.

### CODE REVIEW

**Comment by mmcky** [comment]
@AakashGfude that looks like a good short term solution. 

It would be nice to have the `menubar` in a repo at some point to have a single point of update. But maybe that is best done when we build more `theme` infrastructure?

**Comment by mmcky** [comment]
assuming this config works of course `:-)` -- doesn't look like the menubar is in the `preview`.

We could just have the `<script>` in the `template` folder right? And then reference the assets bucket?

**Comment by AakashGfude** [comment]
aah yeah. should have made this a draft PR. the functionality in `qe-theme` is still at works.

**Comment by AakashGfude** [comment]
mostly made this PR beforehand. to get validation about this approach from you :)

**Comment by AakashGfude** [comment]
@mmcky  the menubar should be in the preview now.

**Comment by mmcky** [comment]
nice work @AakashGfude

**Pull request merged**
