### PR TITLE
Adding Performance Evaluation to Numpy Exercise 

### LINKED ISSUE #230: Add speed comparison for broadcasting exercise in NumPy lecture
I saw that there was a new exercise in the NumPy lecture ([Exercise 9.4](https://python-programming.quantecon.org/numpy.html#exercises)), but I thought maybe it would be more useful for illustrating broadcasting if the reader is asked to use compare the speeds of broadcasting vs. using the for-loop they write.

### PR DESCRIPTION
**Pull request by HumphreyYang**
Hi @mmcky,

This resolves #230. Could you please kindly review this PR and let me know if there is anything I could change?

Many thanks

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @HumphreyYang I think this is a good addition.

**Comment by mmcky** [comment]
@jstac if you approve then I'll merge.

**Comment by jstac** [comment]
Thanks @HumphreyYang , nice work.

My only comment is that in #230 I suggested "adding a second part to the exercise where 4 is replaced by a large number and the reader is asked to time a for loop against the broadcast implementation."

In other words, the reader first replicates on a small example to make sure that they are getting the same result, and then tests the two versions on a larger example to investigate timing.

Do you think this is worthwhile?

**Comment by HumphreyYang** [comment]
Hi @jstac, 

I have added back the sample example. Could you have another look at the newest deployment?

Many thanks.

**Comment by jstac** [comment]
Perfect.  Thanks @HumphreyYang!  Merging.

**Pull request merged**
