### PR TITLE
MAINT: update quantecon-book-theme=0.2.0

### PR DESCRIPTION
**Pull request by mmcky**
This PR updates to `quantecon-book-theme=0.2.0`

### CODE REVIEW

**Comment by mmcky** [comment]
@shlff this is a build of: https://python-programming.quantecon.org/intro.html using the latest `quantecon-book-theme`. 

@AakashGfude has done some nice work on refactoring our theme and adding some new features. 

It would be great if you could spend a bit of time comparing the current live site with this PR build (as a double check). 

Hopefully you won't find many differences :-)

**Comment by mmcky** [comment]
@shlff also just to clarify - there is no need to recheck the whole site. Just wanted another set of eyes to:

1. do some random spot checks
2. look for some of the issues that have cropped up before

**Comment by shlff** [comment]
Thanks @mmcky , I randomly selected 3 lectures and here are the differences I spotted (maybe not issues; left: live website, right: preview of this PR):

[x] added signs:
 
Screen Shot 2021-05-10 at 1 31 55 pm

[x] Bold font for subsubsections
Screen Shot 2021-05-10 at 1 32 43 pm

[x] some problematic Latex output generated by code
Screen Shot 2021-05-10 at 1 34 34 pm

[x] different color for quoted in-text code
Screen Shot 2021-05-10 at 1 36 59 pm

[x] different style for quoted between-text code
Screen Shot 2021-05-10 at 1 37 57 pm

[x] extra spaces above and below the code
Screen Shot 2021-05-10 at 1 39 21 pm

**Comment by mmcky** [comment]
nice work @shlff -- really helpful. thank you.

**Comment by mmcky** [comment]
@AakashGfude any ideas on the `LaTeX` issue for output. Maybe I should change the priorities in the `_config.yml` to promote svg above LaTeX. Is mathjax not parsing the output blocks perhaps?

**Comment by mmcky** [comment]
@shlff I am unable to replicate that issue in `about_py` for the `sympy` math output. Can you let me know what browser you're using.

I have `safari` running

Screen Shot 2021-05-10 at 2 22 10 pm

**Comment by shlff** [comment]
> @shlff I am unable to replicate that issue in `about_py` for the `sympy` math output. Can you let me know what browser you're using.
> 
> I have `safari` running
> 
> Screen Shot 2021-05-10 at 2 22 10 pm

Thanks @mmcky . I double-checked it again and didn't see the same issue either. Please ignore this issue.

**Comment by mmcky** [comment]
thanks again @shlff I think these difference in style are OK. It is really helpful to have these differences documented like this though.

I will go ahead and merge this to update the theme. 

cc: @jstac

**Pull request merged**
