### PR TITLE
MAINT: Upgrade software stack

### PR DESCRIPTION
**Pull request by mmcky**
This PR upgrades to:

- anaconda==2023.09
- python=3.11
- quantecon-book-theme==0.6.0

### CODE REVIEW

**Comment by mmcky** [comment]
@HumphreyYang would you have time to look into this link checker result?

**Comment by mmcky** [comment]
- [x] re-run without cache

**Comment by HumphreyYang** [comment]
Many thanks @mmcky,

The link checker is all green now.

**Comment by mmcky** [comment]
thanks @HumphreyYang love your work.

**Comment by mmcky** [comment]
- [ ] re-enable the build `cache`

**Comment by mmcky** [comment]
@HumphreyYang @HengchengZhang if you had 10minutes would you mind to look through the latest deployment and let me know if you spot any issues or regressions.

**Comment by HengchengZhang** [comment]
Hi Matt, the new search bar and the dark mode looks all good to me. 

One minor thing I can mention is that the color of code block in dark mode, they are now the same color as in bright mode with a dark background. I think it would be better to have a seperate color map for that if possible? 

It is still great if we use the current theme.

**Comment by mmcky** [comment]
> Hi Matt, the new search bar and the dark mode looks all good to me.
> 
> One minor thing I can mention is that the color of code block in dark mode, they are now the same color as in bright mode with a dark background. I think it would be better to have a seperate color map for that if possible?
> 
> It is still great if we use the current theme.

Thanks @HengchengZhang -- I agree we need to make improvements to the theme. Are you indicating that `quantecon-book-theme==0.6.0` is worse than our current live site which uses `quantecon-book-theme==0.5.3`?

**Comment by HengchengZhang** [comment]
> > Hi Matt, the new search bar and the dark mode looks all good to me.
> > One minor thing I can mention is that the color of code block in dark mode, they are now the same color as in bright mode with a dark background. I think it would be better to have a seperate color map for that if possible?
> > It is still great if we use the current theme.
> 
> Thanks @HengchengZhang -- I agree we need to make improvements to the theme. Are you indicating that `quantecon-book-theme==0.6.0` is worse than our current live site which uses `quantecon-book-theme==0.5.3`?

Hi @mmcky I think the new `quantecon-book-theme==0.6.0` is better than current site but the code part can be improved. But still the new theme is pretty nice.

**Comment by mmcky** [comment]
thanks @HumphreyYang and @HengchengZhang for your review and comments. 

Upgrading to the latest versions now.

**Pull request merged**
