### PR TITLE
MAINT: remove %matplotlib inline and contents directives

### PR DESCRIPTION
**Pull request by mmcky**
This PR

- [x] removes `%matplotlib inline` and associated `figsize` settings
- [x] removes `contents` directives as not needed
- [x] validate the preview visually (spot checking)

### CODE REVIEW

**Comment by mmcky** [comment]
- [x] confirm linkchecker are false positives

**Comment by mmcky** [comment]
@jstac I think this is looking good.

**Comment by jstac** [comment]
Many thanks @mmcky .  If you think it's necessary please get another set of eyes to review.  Otherwise please go ahead and merge.

**Comment by mmcky** [comment]
thanks @jstac I have done quite a few spot checks so I will merge.

**Pull request merged**
