### PR TITLE
ENH: Update to quantecon-book-theme==0.6.1

### PR DESCRIPTION
**Pull request by mmcky**
This PR updates to `0.6.1`

https://github.com/QuantEcon/quantecon-book-theme/releases/tag/v0.6.1

### CODE REVIEW

**Comment by mmcky** [comment]
@AakashGfude thanks for this. 

Is there a way to use an inverted `quantecon` logo for dark theme?

Also is there a lighter colour we can use for the right hand table of contents

Screenshot 2023-10-18 at 2 15 31 pm

also the title

Screenshot 2023-10-18 at 2 15 48 pm

Looking like a big improvement thought. Thanks. 

cc: @HumphreyYang @HengchengZhang

**Comment by AakashGfude** [comment]
Thanks @mmcky . Yes, I will add a lighter color. Since that image is jpg, so, if I invert the colour, the logo colour changes as well, for example: 
Screen Shot 2023-10-18 at 2 33 22 pm

We can either try to create a new image for dark mode, or use this?

Thanks for the right hand toc, will add the same styling as left-hand toc: 
Screen Shot 2023-10-18 at 2 32 56 pm

**Comment by mmcky** [comment]
@DrDrij has a QuantEcon logo for dark backgrounds. I will try and dig it up. But it would be great if we can use a different logo to support dark mode.

**Comment by mmcky** [comment]
@AakashGfude here is one for black backgrounds

qe-logo-on-black

**Comment by AakashGfude** [comment]
Thanks @mmcky . I will get it done next week. When I am back to Canberra

**Comment by mmcky** [comment]
closing as we will upgrade to `0.6.2` instead with improved dark theme support

**Pull request closed without merging**
